db:
    mode: mysql
    db_name: fast_db
    host: 127.0.0.1
    port: 3306
    user: root
    password: "123456"
redis:
    addr: "127.0.0.1:6379"
    password: ""
    db: 1
system:
    mode: release  # release debug
    ip: 127.0.0.1
    port: 8080
jwt:
    expires: 8   # 有效期单位小时
    issuer: chenxi   # 签发人
    key: angrinsss   # 密钥
upload:
    max_size: 2  # 最大上传文件大小
    dir: "./images"
    allow_ext:
        - ".jpg"
        - ".png"
        - ".gif"
        - ".jpeg"
        - ".webp"
site:
    login:
        captcha: true